# -*- coding: utf-8 -*-
"""Task-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zOTXyBDVGyWAelNn6TrTngR4ONsRsl-q
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AAPL.csv")
df

print(df.head())

print(df.shape)

print(df.info())

#clean
df = df.dropna()

df = df.drop_duplicates()
df

#Avg
avg_open = df['Open'].mean()
avg_close = df['Close'].mean()

print(f"Average Open Price: {avg_open:.2f}")
print(f"Average Close Price: {avg_close:.2f}")

highestinhigh = df['High'].max()
lowestinlow = df['Low'].min()

print(f"Highest High Price: {highestinhigh:.2f}")
print(f"Lowest Low Price: {lowestinlow:.2f}")

df['Delta'] = df['Close'] - df['Open']
print(df[['Open', 'Close', 'Delta']])

