# -*- coding: utf-8 -*-
"""shopify_stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2nV-aYZIBOZ6_oHyvWLE9H7EhlhlghB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Load data
df = pd.read_csv("shopify_stock.csv")
df

# 2. Understand data
print(df.head())

print(df.shape)

print(df.info())

print(df.describe())

print(df.info())

df["date"] = pd.to_datetime(df["date"], utc=True)
#df["date"] = pd.to_datetime(df["date"], errors="coerce", utc=True)

df['date'].dtype

# 4. Check missing values
print(df.isnull().sum())

df = df.dropna()

# 5. Remove duplicates
df = df.drop_duplicates()
df

# 6. Sort by date
df = df.sort_values("date")

# 7. Calculate Daily Delta
df["Daily_Delta"] = df["close"] - df["open"]

# 8. Calculate Daily Return
df["Daily_Return"] = (
    (df["close"] - df["open"]) / df["open"]
) * 100

# 9. Display calculated columns
print(df[
    ["date", "open", "close", "Daily_Delta", "Daily_Return"]
].head())

# 10. Volume analysis

average_volume = df["volume"].mean()
maximum_volume = df["volume"].max()
minimum_volume = df["volume"].min()

print("Average Volume:", average_volume)
print("Maximum Volume:", maximum_volume)

#anomaly or unsual rule
threshold = 2 * average_volume

anomalous_days = df[df["volume"] > threshold]

print("\nAnomalous Trading Days:")
print(
    anomalous_days[
        [
            "date",
            "open",
            "close",
            "Daily_Delta",
            "Daily_Return",
            "volume"
        ]
    ]
)

# 13. Return statistics distributions

mean_return = df["Daily_Return"].mean()
variance_return = df["Daily_Return"].var()
std_return = df["Daily_Return"].std()

print("Mean Return:", mean_return)
print("Variance:", variance_return)
print("Standard Deviation:", std_return)

#visualization
plt.figure(figsize=(10,5))

plt.plot(df["date"], df["close"])

plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.title("Shopify Closing Price Trend")
plt.show()

# 15. Volume chart

plt.figure(figsize=(10,5))

plt.plot(df["date"], df["volume"])

plt.xlabel("Date")
plt.ylabel("Volume")
plt.title("Shopify Trading Volume Trend")

plt.show()
plt.savefig("chart.png")

# 16. Return distribution

plt.figure(figsize=(10,5))

sns.histplot(df["Daily_Return"], bins=30)

plt.xlabel("Daily Return (%)")
plt.ylabel("Number of Days")
plt.title("Shopify Daily Return Distribution")

plt.show()

