# -*- coding: utf-8 -*-
"""Task-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwdPDtPwI77AK9OLTzGLuHFDyMd05cwI
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df =pd.read_csv("/content/drive/MyDrive/Colab Notebooks/StudentsPerformance.csv")
df

df.head()

df.tail()

df.describe()

df.shape

df.columns

df.info()

df.isnull().sum()

df.duplicated().sum()

score_column=['math score','reading score','writing score']
df[score_column].describe()

df[score_column].mean()

df[score_column].median()

df[score_column].std()

df[score_column].quantile()

df["Total Score"]=(df["math score"]+df["reading score"]+df["writing score"])

df.head()

df['percentage']=df['Total Score'] /300 * 100

df.head()

df.tail()

