# -*- coding: utf-8 -*-
"""Task-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1amOuhNuu4YrH4tojGri0wJ-wPWM52A6x
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/healthcare_dataset.csv")

print(df.head())

print(df.info())

print(df.isnull())

df = df.dropna()

#2
df['Admission_Type'] = df['Admission_Type'].str.lower()

print(df['Admission_Type'].head())

df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], utc=True,)
df['Admission_Date'].dtype

df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"], utc=True,)
df['Discharge_Date'].dtype

df["Total days"] = df["Discharge_Date"] - df["Admission_Date"]
df





