# -*- coding: utf-8 -*-
"""Task-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJynaoLSPMjEQ2i8BFR4kbNJ5ccrLBad
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df =pd.read_csv("/content/drive/MyDrive/Colab Notebooks/studentperformance_preproccesed.csv")
df

df.info()

df.columns

df.shape

score_columns=['math score','reading score','writing score',]

df[score_columns].head()

demographic_columns = ['gender','race/ethnicity','parental level of education','lunch','test preparation course']

df[demographic_columns].head()

df['gender'].unique()

df['parental level of education'].unique()

df['lunch'].unique()

df['test preparation course'].unique()

"""## 1. Grouped bar charts"""

parental_scores = df.groupby('parental level of education')[score_columns].mean()
parental_scores

parental_scores.plot(kind='bar',figsize=(12,6))
plt.title('Average Exam Scores by Parental Level of Education')
plt.xlabel('Parental Level of Education')
plt.ylabel('Average Score')
plt.xticks(rotation=45)
plt.legend(title='Subject')
plt.show()

lunch_scores = df.groupby('lunch')[score_columns].mean()
lunch_scores

lunch_scores.plot(kind='bar',figsize=(8,6))
plt.title('Average Exam Scores by Lunch Type')
plt.xlabel('Lunch Type')
plt.ylabel('Average Score')
plt.xticks(rotation=0)
plt.legend(title='Subject')
plt.show()

"""Parental education and lunch type together."""

edu_order = ['some high school','high school','some college',"associate's degree","bachelor's degree","master's degree"]

math_scores = df.pivot_table(index='parental level of education', columns='lunch', values='math score', aggfunc='mean').reindex(edu_order)
math_scores

math_scores.plot(kind='bar',figsize=(12,6))
plt.title('Average Math Score by Parental Education and Lunch Type')
plt.xlabel('Parental Level of Education')
plt.ylabel('Average Score')
plt.xticks(rotation=45)
plt.legend(title='Lunch', loc='upper left')
plt.show()

reading_scores = df.pivot_table(index='parental level of education', columns='lunch', values='reading score', aggfunc='mean').reindex(edu_order)
reading_scores.plot(kind='bar',figsize=(12,6))
plt.title('Average Reading Score by Parental Education and Lunch Type')
plt.xlabel('Parental Level of Education')
plt.ylabel('Average Score')
plt.xticks(rotation=45)
plt.legend(title='Lunch', loc='upper left')
plt.show()

writing_scores = df.pivot_table(index='parental level of education', columns='lunch', values='writing score', aggfunc='mean').reindex(edu_order)
writing_scores.plot(kind='bar',figsize=(12,6))
plt.title('Average Writing Score by Parental Education and Lunch Type')
plt.xlabel('Parental Level of Education')
plt.ylabel('Average Score')
plt.xticks(rotation=45)
plt.legend(title='Lunch', loc='upper left')
plt.show()

percentage_scores = df.pivot_table(index='parental level of education', columns='lunch', values='percentage', aggfunc='mean').reindex(edu_order)
percentage_scores

percentage_scores.plot(kind='bar',figsize=(12,6))
plt.title('Average Percentage by Parental Education and Lunch Type')
plt.xlabel('Parental Level of Education')
plt.ylabel('Average Percentage')
plt.xticks(rotation=45)
plt.legend(title='Lunch', loc='upper left')
plt.show()

"""## 2. Box plots: test preparation"""

plt.figure(figsize=(6,5))
sns.boxplot(x='test preparation course', y='math score', data=df)
plt.title('Math Score by Test Preparation')
plt.show()

plt.figure(figsize=(6,5))
sns.boxplot(x='test preparation course', y='reading score', data=df)
plt.title('Reading Score by Test Preparation')
plt.show()

plt.figure(figsize=(6,5))
sns.boxplot(x='test preparation course', y='writing score', data=df)
plt.title('Writing Score by Test Preparation')
plt.show()

df.groupby('test preparation course')[score_columns].mean()

df.groupby('test preparation course')[score_columns].std()

df.groupby('test preparation course')[score_columns].var()

"""## 3. Scatter plots and correlation heatmap"""

plt.figure(figsize=(6,5))
sns.scatterplot(x='math score', y='reading score', data=df)
plt.title('Math vs Reading')
plt.show()

plt.figure(figsize=(6,5))
sns.scatterplot(x='math score', y='writing score', data=df)
plt.title('Math vs Writing')
plt.show()

plt.figure(figsize=(6,5))
sns.scatterplot(x='reading score', y='writing score', data=df)
plt.title('Reading vs Writing')
plt.show()

df[score_columns].corr()

plt.figure(figsize=(6,5))
sns.heatmap(df[score_columns].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap of Exam Scores')
plt.show()