# -*- coding: utf-8 -*-
"""task8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6SrpPJEcjFfEm9mtlr_tBZ0hDBZSF9z

# Student Performance Analysis
Grouped bar charts, box plots, scatter plots, correlation heatmap and an equity report.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("StudentsPerformance.csv")
df

df.shape

df.info()

df.isnull().sum()

df.duplicated().sum()

score_column = ['math score', 'reading score', 'writing score']
df[score_column].describe()

df['Total Score'] = df['math score'] + df['reading score'] + df['writing score']
df['percentage'] = df['Total Score'] / 300 * 100
df.head()

"""## 1. Grouped bar charts
Average score for each parental education level, split by lunch type.
"""

edu_order = ['some high school', 'high school', 'some college',
             "associate's degree", "bachelor's degree", "master's degree"]

plt.figure(figsize=(10, 5))
sns.barplot(x='parental level of education', y='math score', hue='lunch', data=df, order=edu_order, errorbar=None)
plt.title('Average Math Score by Parental Education and Lunch Type')
plt.xticks(rotation=30)
plt.show()

plt.figure(figsize=(10, 5))
sns.barplot(x='parental level of education', y='reading score', hue='lunch', data=df, order=edu_order, errorbar=None)
plt.title('Average Reading Score by Parental Education and Lunch Type')
plt.xticks(rotation=30)
plt.show()

plt.figure(figsize=(10, 5))
sns.barplot(x='parental level of education', y='writing score', hue='lunch', data=df, order=edu_order, errorbar=None)
plt.title('Average Writing Score by Parental Education and Lunch Type')
plt.xticks(rotation=30)
plt.show()

plt.figure(figsize=(10, 5))
sns.barplot(x='parental level of education', y='percentage', hue='lunch', data=df, order=edu_order, errorbar=None)
plt.title('Overall Average Percentage by Parental Education and Lunch Type')
plt.xticks(rotation=30)
plt.show()

df.groupby('lunch')[score_column + ['percentage']].mean()

df.groupby('parental level of education')[score_column + ['percentage']].mean()

"""## 2. Box plots
Score spread for students who completed test preparation vs. those who did not.
"""

plt.figure(figsize=(6, 5))
sns.boxplot(x='test preparation course', y='math score', data=df)
plt.title('Math Score by Test Preparation')
plt.show()

plt.figure(figsize=(6, 5))
sns.boxplot(x='test preparation course', y='reading score', data=df)
plt.title('Reading Score by Test Preparation')
plt.show()

plt.figure(figsize=(6, 5))
sns.boxplot(x='test preparation course', y='writing score', data=df)
plt.title('Writing Score by Test Preparation')
plt.show()

df.groupby('test preparation course')[score_column].mean()

df.groupby('test preparation course')[score_column].std()

df.groupby('test preparation course')[score_column].var()

"""## 3. Scatter plots and correlation heatmap"""

plt.figure(figsize=(6, 5))
sns.scatterplot(x='math score', y='reading score', data=df)
plt.title('Math vs Reading')
plt.show()

plt.figure(figsize=(6, 5))
sns.scatterplot(x='math score', y='writing score', data=df)
plt.title('Math vs Writing')
plt.show()

plt.figure(figsize=(6, 5))
sns.scatterplot(x='reading score', y='writing score', data=df)
plt.title('Reading vs Writing')
plt.show()

df[score_column].corr()

plt.figure(figsize=(6, 5))
sns.heatmap(df[score_column].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()