# -*- coding: utf-8 -*-
"""Task-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O5NBiXol-K0Dbazz_3lbaybTJGCnxgfl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/healthcare_dataset (1).csv")
df

df.head()

df.shape

df.describe()

print(df.isnull().sum())

df = df.dropna()

df["Date of Admission"] = pd.to_datetime(df["Date of Admission"], utc=True)
df['Date of Admission'].dtype

df["Discharge Date"] = pd.to_datetime(df["Discharge Date"], utc=True)
df['Discharge Date'].dtype

df["Hospital_Stays"] = df["Discharge Date"] - df["Date of Admission"]
df['Hospital_Stays'] = df['Hospital_Stays'].dt.days
df

billing = df.groupby(["Medical Condition", "Insurance Provider"])["Billing Amount"].sum().unstack()
billing

billing.plot(
    kind="bar",
    stacked=True,
    figsize=(10, 6)
)
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.title("Billing Amount by Medical Condition and Insurance Provider")
plt.xticks(rotation=45)
plt.legend(title="Insurance Provider")
plt.show()

plt.figure(figsize=(10, 6))
sns.violinplot(
    x="Medical Condition",
    y="Hospital_Stays",
    data=df,
)
plt.title("Distribution of Hospital Stays by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Hospital Stays")
plt.show()

df['Admission Month'] = df['Date of Admission'].dt.to_period('M')
df['Admission Month']

monthly_admissions = df.groupby('Admission Month').size()
monthly_admissions

plt.figure(figsize=(10, 6))

monthly_admissions.plot(kind='line', marker='o')
plt.title('Monthly Admissions')
plt.xlabel('Month')
plt.ylabel('Number of Admissions')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

correlation_matrix = df[['Age', 'Hospital_Stays', 'Billing Amount']].corr()
correlation_matrix

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

"""# Executive Summary — Healthcare Dataset EDA (Week 6)

## Purpose

This analysis was conducted to extract operational and financial insights from a hospital's patient-level records. The objective was to understand how billing costs, length of stay, and admission volume vary across medical conditions, insurance providers, and time — providing a foundation for cost management, capacity planning, and further predictive modeling.

## Scope and Methodology

The analysis followed a standard four-stage EDA (Exploratory Data Analysis) pipeline:

1. **Data Preparation** — Raw patient records were loaded and audited for missing values, which were removed to ensure analytical accuracy. Admission and discharge dates were converted into a proper date format to enable time-based calculations.
2. **Feature Engineering** — Two derived metrics were created: **Length of Stay** (days between admission and discharge) and **Admission Month** (for trend tracking), since neither existed directly in the raw data but were necessary for the questions being asked.
3. **Financial Analysis** — Total billing amounts were broken down by medical condition and insurance provider to identify which condition/insurer combinations drive the highest costs.
4. **Clinical and Temporal Analysis** — Length-of-stay patterns were examined across conditions, admission volumes were tracked month-over-month, and relationships between patient age, stay duration, and billing amount were tested statistically.

## What Each Graph Shows

- **Stacked Bar Chart (Billing by Condition & Insurer):** Shows total billing amount for each medical condition, split into colored segments by insurance provider — makes it easy to see which condition/insurer pairs contribute most to overall costs.
- **Violin Plot (Hospital Stay Distribution):** Shows the full spread of stay lengths for each medical condition, including where most values cluster and how much they vary — not just an average.
- **Line Chart (Monthly Admissions):** Plots the number of patient admissions per month, making it easy to spot upward/downward trends or seasonal patterns over time.
- **Heatmap (Correlation Matrix):** Displays how strongly Age, Hospital Stays, and Billing Amount are related to one another, with values from -1 to +1 and color intensity indicating strength of the relationship.

## Key Areas of Insight

| Analysis | Business Question Answered |
|---|---|
| Billing by Condition & Insurer | Which conditions and insurers are associated with the largest total healthcare spend? |
| Stay Duration Distribution | Which conditions are linked to longer or more unpredictable hospital stays? |
| Monthly Admissions Trend | Is patient volume growing, shrinking, or seasonal? |
| Correlation Analysis (Age, Stay, Billing) | Do older patients or longer stays correspond to higher billing amounts? |
"""